### ISSUE TITLE
Upgrade raw data API database and backend VM resource capacity

### ISSUE THREAD

**Issue by kshitijrajsharma** [hotosm/raw-data-api#117]
Currently, the raw-data production infrastructure is under-provisioned for our needs.

|Component|CPU|RAM|Machine IOPS|Disk|Disk IOPS|Monthly Cost|
|---|---|---|---|---|---|---|
| Database|2 vCores | 8 GB |3200 |2048 GB|7500|$ 435|
| Backend VM|2 vCPU|4 GB |?|32 GB root + 1000 GB data vol| 500|$ 78|

I propose the following specs to improve performance:

- [x] Production Instance with 4 vCPU and 32GB RAM
- [ ] Production Database with 2 TB storage ( Elastic storage enabled ) - We can set max limit of 5 TB 
- [ ] Brainstorm to launch multiple containers based on CPU usage / Memory usage and may be other necessary indicators  ( Just like we did on Galaxy-API )

**Comment by kshitijrajsharma** [comment]
This Spec is based on the research I did before for loading planet with underpass ec2 and galaxy RDS

**Comment by eternaltyro** [comment]
@kshitijrajsharma I have increased VM capacity. Now moving on to the DB disk.

**Comment by eternaltyro** [comment]
@kshitijrajsharma Storage auto-grow is unfortunately not available in this type of databases on Azure. I can grow the disk at a later stage if you need me to. If that is not acceptable, we can increase storage right away. It is currently already 2TB.
