### ISSUE TITLE
[FEATURE] Output PMTile format

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/raw-data-api#136]
**Is your feature request related to a problem? Please describe.**
- Currently various output formats supported by ogr2ogr are supported, such as MBTiles.
- PMTiles are like MBTiles, but cloud-optimised and the latest v3 spec has some neat optimisations.
- PMTiles cannot be produced directly with ogr2ogr (yet).

**Describe the solution you'd like**
- Tools like [tippecanoe](https://github.com/felt/tippecanoe) or [go-pmtiles](https://github.com/protomaps/go-pmtiles) can produce PMTiles.
- I suggest we either:

## 1)
- Install tippecanoe from source in a multi-stage dockerfile, then copy the bins into the run stage: https://github.com/felt/tippecanoe/blob/2b133a1def98f1adc14a486fe140930ce9174567/Dockerfile#L18
- Produce GeoJSON in an intermediate step (either directly from PostGIS, or with ogr2ogr).
- Convert with PMTiles: `tippecanoe -zg --projection=EPSG:4326 -o cb_2018_us_zcta510_500k_nolimit.pmtiles -l zcta cb_2018_us_zcta510_500k.json`

## 2)
- Install the go-pmtiles binary alongside ogr2ogr.
- Produce MBTiles in an intermediate step with ogr2ogr.
- Convert to PMTiles with the `pmtiles` binary: `pmtiles convert INPUT.mbtiles OUTPUT.pmtiles`.

**These two approaches could be benchmarked and compared to find the most efficient.**

**Comment by ivangayton** [comment]
Whoa, that's interesting; I'd not heard of PMTiles before! 

I've done a bit of quick searching, but I can't immediately see if PMTiles can be easily styled (I think the biggest drawback of MVTiles is the poor support for styling outside of MapBox Studio).

@spwoodcock do you happen to know offhand if there is a straightforward way to style PMTiles, either in Openlayers, some other web map framework, or on mobile?

**Comment by spwoodcock** [comment]
It's reasonably new - the guys from Protomaps have been at FOSS4G the past few years & make some pretty cool stuff.

PMTiles are just a vector tile, so supported in both OpenLayers and MapLibre GL JS.
Example for OpenLayers: https://openlayers.org/en/latest/examples/pmtiles-elevation.html

Styling should be done on the client side.

Styling in OpenLayers: https://openlayers.org/workshop/en/vectortile/
Styling in MapLibre: https://maplibre.org/maplibre-style-spec/

I assume MapLibre is natively a bit better at this, as vector tiles is what they are all about.
I have never tried in OpenLayers, but it doesn't look too tricky.

**Comment by spwoodcock** [comment]
bump to keep open

**Comment by kshitijrajsharma** [comment]
I didn't noticed this issue before ! This was closed by #151
