### ISSUE TITLE
[FEATURE] Use sozipfile for zip creation

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/raw-data-api#179]
**Is your feature request related to a problem? Please describe.**

- Currently files are zipped using Python zipfile module.
- [sozipfile](http://download.osgeo.org/gdal/presentations/SOZip%20%28FOSS4G%202023%29.pdf) is a new format that is integrated into GDAL.
- It's use case is to add compression to formats that do not support it: flatgeobuf, geopackage, shapefile, etc.
- There is a [drop in replacement](https://github.com/sozip/sozipfile) for the Python zipfile module:

```python
import sozipfile.sozipfile as zipfile
```

**Describe the solution you'd like**

- Use sozipfile instead of zipfile for `.zip` generation.
- All sozipfile generated zips are fully backward compatible with standard zip readers.
- sozipfile allows RANGE requests to be used on the file, so only the specific part that is required is extracted.
  - This required the vsicurl driver in GDAL, so for now is only.
  - A user could use QGIS to stream the data extract directly from the bucket.
- I am uncertain about JS reader capability for sozip, but we could explore that in the future.

**Describe alternatives you've considered**

- [cotar](https://github.com/linz/cotar) is the same for `.tar` format, which I assume GZip compression should work for. But there is no Python or GDAL support.

**Comment by kshitijrajsharma** [comment]
- Fixed by #180
