### ISSUE TITLE
[BUG] flatgeobuf files generated with unknown geometry

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/raw-data-api#210]
**Describe the bug**

The flatgeobuf files generated with mixed geometry types result in an 'Unknown' geometry type:

![image](https://github.com/hotosm/raw-data-api/assets/78538841/09c107f1-c318-4da5-ad3a-081c0b04e7c7)

Check with `ogrinfo -al /path/to/your/file.fgb`.

This is fine to load into QGIS, but fails when importing into tools with stricter geometry checking, e.g. PostGIS imports fail.

**To Reproduce**

- Generate a data extract in flatgeobuf format with multiple geometry types on export.hotosm.org
- Inspect the flatgeobuf with ogrinfo.
- Attempt to load flatgeobuf into PostGIS, e.g:

```SQL
        DROP TABLE IF EXISTS public.temp_fgb CASCADE;

        SELECT ST_FromFlatGeobufToTable('public', 'temp_fgb', :fgb_bytes);

        SELECT jsonb_build_object(
            'type', 'FeatureCollection',
            'features', jsonb_agg(feature)
        ) AS feature_collection
        FROM (
            SELECT jsonb_build_object(
                'type', 'Feature',
                'geometry', ST_AsGeoJSON(fgb_data.geom)::jsonb,
                'properties', jsonb_build_object(
                    'osm_id', fgb_data.osm_id,
                    'tags', fgb_data.tags,
                    'version', fgb_data.version,
                    'changeset', fgb_data.changeset,
                    'timestamp', fgb_data.timestamp

                )::jsonb
            ) AS feature
            FROM (
                SELECT
                    geom,
                    NULL as osm_id,
                    NULL as tags,
                    NULL as version,
                    NULL as changeset,
                    NULL as timestamp
                FROM ST_FromFlatGeobuf(null::temp_fgb, :fgb_bytes)
            ) AS fgb_data
        ) AS features;
```

**Expected behavior**

- The flatgeobuf file has geometry type specified, so it can be loaded into PostGIS.

**Possible solution**

- This setting in ogr2ogr can help to control this behaviour: https://gdal.org/programs/ogr2ogr.html#cmdoption-ogr2ogr-nlt
- Mixed polygon/multipolygon, or polyline/multipolyline can be upgraded with option `PROMOTE_TO_MULTI`, but this doesn't help us much.
- The only solution I could come up with is to use `-nlt GEOMETRYCOLLECTION`.
- This would wrap each individual geometry inside a GeometryCollection, so overall the type is all GeometryCollection (which is a valid thing to do, although not necessarily recommended).
- When we import into PostGIS each geom would be of type GeometryCollection, but this can be solved by stripping the geom out prior to import.
- For example, if we converted to geojson, we could remove the GeometryCollection wrapper by accessing the `geometries` key for each geom in the FeatureCollection.
- The update can be included by adding the flag here (perhaps as an optional config option): https://github.com/hotosm/raw-data-api/blob/46635f527333bf7e6bd4c14ce9e4e749eb00ad44/src/app.py#L565C22-L565C217

We should probably also specify: `-lco SPATIAL_INDEX=YES` to generate a spatial index for the file (it makes it slightly larger, but is very useful for doing spatial queries on the data).

@kshitijrajsharma would you accept a PR for this?
1. Add optional flag to wrap all flatgeobuf geoms in standardised Geometry collection.
2. Add spatial index to flatgeobuf files by default.

**Comment by kshitijrajsharma** [comment]
Sure , Thanks Sam for the report ! I will have a look and sure PR is welcome !

**Comment by kshitijrajsharma** [comment]
I can't reproduce this issue , can you check following attachment ? 
[Pokhara_all_features_fgb_uid_d9185e72-2e89-47a2-a632-bfb64c81a3e9.zip](https://github.com/hotosm/raw-data-api/files/14355120/Pokhara_all_features_fgb_uid_d9185e72-2e89-47a2-a632-bfb64c81a3e9.zip)


Looks okay from my side : 
<img width="464" alt="image" src="https://github.com/hotosm/raw-data-api/assets/36752999/6d304cd8-2bac-413b-8a22-32654d0d53e6">

**Comment by kshitijrajsharma** [comment]
Okay I see what you mean , this one 
<img width="454" alt="image" src="https://github.com/hotosm/raw-data-api/assets/36752999/c83b24f9-6b30-4777-86d9-5335c1111635">

**Comment by spwoodcock** [comment]
This option has been added and works as intended. The flatgeobuf file can be loaded into a PostGIS table now.

However, the resulting GeometryCollection wrapped geometries cannot be loaded in QGIS.
This is not an issue unique to flatgeobuf, as GeoJSON GeometryCollection type is not supported yet by QGIS either https://github.com/qgis/QGIS/issues/32747
